# Generated by Django 2.1.1 on 2018-09-13 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=32, verbose_name='Activation Key')),
                ('expire', models.DateTimeField(verbose_name='Expire')),
                ('user_id', models.ForeignKey(on_delete='CASCADE', related_name='activations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
